"""empty message

Revision ID: 143a952284ca
Revises: 
Create Date: 2025-09-19 10:22:24.938126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143a952284ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('rif', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('fecha_creacion_cliente', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('avance_real', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wbs_code', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('avance_real', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato', sa.String(length=100), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=100), nullable=True),
    sa.Column('estado_contrato', sa.String(length=50), nullable=True),
    sa.Column('facturado', sa.String(length=10), nullable=True),
    sa.Column('plan_anterior', sa.String(length=100), nullable=True),
    sa.Column('plan_facturado', sa.String(length=100), nullable=True),
    sa.Column('plan_aprovisionado', sa.String(length=100), nullable=True),
    sa.Column('plan_servicio', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado_servicio', sa.String(length=50), nullable=True),
    sa.Column('dominio', sa.String(length=100), nullable=True),
    sa.Column('dns_dominio', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('ubicacion_sala', sa.String(length=100), nullable=True),
    sa.Column('cantidad_ru', sa.Integer(), nullable=True),
    sa.Column('cantidad_m2', sa.Integer(), nullable=True),
    sa.Column('cantidad_bastidores', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('nombre_servidor', sa.String(length=100), nullable=True),
    sa.Column('nombre_nodo', sa.String(length=100), nullable=True),
    sa.Column('nombre_plataforma', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('hdd', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('datastore', sa.String(length=100), nullable=True),
    sa.Column('ip_privada', sa.String(length=50), nullable=True),
    sa.Column('ip_publica', sa.String(length=50), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('ipam', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('fecha_creacion_servicio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wbs_code', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('predecessors', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('avance_real', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('tamaño', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.LargeBinary(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_table('activities')
    op.drop_table('servicios')
    op.drop_table('phases')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('clientes')
    # ### end Alembic commands ###
