"""empty message

Revision ID: 1e5be8759967
Revises: df3824960f18
Create Date: 2025-02-24 14:10:21.749498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e5be8759967'
down_revision = 'df3824960f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
