"""empty message

Revision ID: 920fe6b8ed1c
Revises: 990a7f60bc7e
Create Date: 2025-03-11 15:32:35.087012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920fe6b8ed1c'
down_revision = '990a7f60bc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_publica', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('ip_publica')

    # ### end Alembic commands ###
