"""empty message

Revision ID: 990a7f60bc7e
Revises: 
Create Date: 2025-03-11 12:43:56.803262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990a7f60bc7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_servicio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('plan_servicio')

    # ### end Alembic commands ###
