"""empty message

Revision ID: 9fa9be38bc18
Revises: be295d85dbdd
Create Date: 2025-03-06 15:59:55.526575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fa9be38bc18'
down_revision = 'be295d85dbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('documento')

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('documento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
