"""empty message

Revision ID: df3824960f18
Revises: 6899a867194c
Create Date: 2025-02-18 14:56:53.308208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3824960f18'
down_revision = '6899a867194c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('documento')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('documento')

    # ### end Alembic commands ###
