"""empty message

Revision ID: e5e5559e7626
Revises: 
Create Date: 2025-01-29 12:03:47.967569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e5559e7626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('rif', sa.String(), nullable=True),
    sa.Column('razon_social', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('dominio', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('tipo_servicio', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('contrato', sa.String(), nullable=True),
    sa.Column('plan_aprovisionado', sa.String(), nullable=True),
    sa.Column('plan_facturado', sa.String(), nullable=True),
    sa.Column('detalle_plan', sa.String(), nullable=True),
    sa.Column('sockets', sa.Integer(), nullable=True),
    sa.Column('powerstate', sa.String(), nullable=True),
    sa.Column('ip_privada', sa.String(), nullable=True),
    sa.Column('vlan', sa.String(), nullable=True),
    sa.Column('ipam', sa.String(), nullable=True),
    sa.Column('datastore', sa.String(), nullable=True),
    sa.Column('nombre_servidor', sa.String(), nullable=True),
    sa.Column('marca_servidor', sa.String(), nullable=True),
    sa.Column('modelo_servidor', sa.String(), nullable=True),
    sa.Column('nombre_nodo', sa.String(), nullable=True),
    sa.Column('nombre_plataforma', sa.String(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('hdd', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('tipo_servidor', sa.String(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('facturado', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicios')
    op.drop_table('users')
    op.drop_table('clientes')
    # ### end Alembic commands ###
