"""empty message

Revision ID: e943213b8977
Revises: 
Create Date: 2025-09-19 14:06:12.427390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e943213b8977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('rif', sa.String(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion_cliente', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('edt_structure', sa.String(), nullable=True),
    sa.Column('num_phases', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('contrato', sa.String(), nullable=True),
    sa.Column('estado_contrato', sa.String(), nullable=True),
    sa.Column('estado_servicio', sa.String(), nullable=False),
    sa.Column('dominio', sa.String(), nullable=True),
    sa.Column('dns_dominio', sa.String(), nullable=True),
    sa.Column('tipo_servicio', sa.String(), nullable=False),
    sa.Column('plan_aprovisionado', sa.String(), nullable=True),
    sa.Column('plan_servicio', sa.String(), nullable=True),
    sa.Column('plan_anterior', sa.String(), nullable=True),
    sa.Column('plan_facturado', sa.String(), nullable=True),
    sa.Column('facturado', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_privada', sa.String(), nullable=True),
    sa.Column('ip_publica', sa.String(), nullable=True),
    sa.Column('vlan', sa.String(), nullable=True),
    sa.Column('ipam', sa.String(), nullable=True),
    sa.Column('datastore', sa.String(), nullable=True),
    sa.Column('nombre_servidor', sa.String(), nullable=True),
    sa.Column('nombre_nodo', sa.String(), nullable=True),
    sa.Column('nombre_plataforma', sa.String(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('hdd', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('cantidad_ru', sa.Integer(), nullable=True),
    sa.Column('cantidad_m2', sa.Integer(), nullable=True),
    sa.Column('cantidad_bastidores', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('ubicacion_sala', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion_servicio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('predecessors', sa.String(), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('planned_percent', sa.Float(), nullable=True),
    sa.Column('real_compliance', sa.Float(), nullable=True),
    sa.Column('real_percent', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('accumulated_deviation', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('tamaño', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.LargeBinary(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_table('activities')
    op.drop_table('servicios')
    op.drop_table('phases')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('clientes')
    # ### end Alembic commands ###
